version: "3.5"

services:

  registry:
    image: apache/nifi-registry:0.3.0
    ports:
      - "18080:18080" # UI
    networks:
      - demo

  nifi:
    image: apache/nifi:1.8.0
    ports:
      - "8080:8080" # UI
      - "10000" # Site-to-Site Input Port
    networks:
      - demo

  flowops:
    image: kevdoran/flowops:0.1.0
    networks:
      - demo
    environment:
      - NIFI_URL=http://nifi:8080
      - REGISTRY_URL=http://registry:18080
      - REGISTRY_NAME=DockerRegistry
      - REGISTRY_BUCKET_NAME=Default
    command: [
      # The entrypoint is /bin/bash, the -c flag treats the command string as parts rather than single string arg
      -c, "create-registry-bucket && add-registry-to-nifi"
    ]
    depends_on:
      - registry
      - nifi

networks:
  demo: 